language: python
python:
  - "3.8"
dist: bionic
env:
  global:
    - TRAVIS=true

jobs:
  include:
    - stage: test
      install: skip
      script:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
        - nvm install 14.15.0
        - nvm use 14.15.0
        - make dev_env
        - make tests
      after_success:
        - make coverage
    - stage: dockerize
      install: skip
      script:
        - make docker_push
    - stage: deploy
      install: skip
      script:
        - make heroku

stages:
  - test
  - name: dockerize
    if: branch = master AND type = push AND fork = false
  - name: deploy
    if: branch = master AND type = push AND fork = false
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file_glob: true
#  file:
#    - backend/*
#  skip_cleanup: true
#  on:
#    tags: true

notifications:
  email: false
