branches:
  only:
  - master
language: python
python:
  - "3.8"
  - "3.7"
sudo: required
services:
  - docker
env:
  global:
    - TRAVIS=true
#before_install:
install: true
# before_script:
script:
  - make dev_env
  - make tests
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - source/*
  skip_cleanup: true
  on:
    tags: true

# after_failure:
after_success:
  - coveralls
  - codecov -t $CODECOV_TOKEN
  - make docker
  - test "$TRAVIS_BRANCH"="master" && make heroku

notifications:
  email: false
# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script
