language: python
#before_install:
install: true
# before_script:
script:
  - make dev_env
  - make run
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - source/*
  skip_cleanup: true
  on:
    tags: true

# after_failure:
# after_success:
# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script