language: python
python:
  - "3.8"
  - "3.7"
dist: bionic
env:
  global:
    - TRAVIS=true

jobs:
  include:
    - stage: test
      install:
        - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
        - nvm install 14.15.0
        - nvm use 14.15.0
      script:
        - make dev_env
        - make tests
      after_success:
        - make coverage
    - stage: dockerize
      services: docker
      script:
        - test $TRAVIS_PULL_REQUEST = "false" && make docker_push
    - stage: deploy
      services: docker
      provider: script
        script: make heroku
        on:
          branch: master

stages:
  - test
  - name: dockerize
    if: branch = master
  - name: deploy
    if: branch = master
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file_glob: true
#  file:
#    - backend/*
#  skip_cleanup: true
#  on:
#    tags: true

notifications:
  email: false