language: python
python:
  - "3.8"
  - "3.7"
sudo: required
services:
  - docker
env:
  global:
    - TRAVIS=true
#before_install:
install: true
# before_script:
script:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  - nvm install 14.15.0
  - nvm use 14.15.0
  - make dev_env
  - make tests
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file_glob: true
#  file:
#    - backend/*
#  skip_cleanup: true
#  on:
#    tags: true

# after_failure:
after_success:
  - make coverage
<<<<<<< HEAD
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && make docker_push
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && make heroku
=======
  - test "$TRAVIS_BRANCH"="master" && make docker
  - test "$TRAVIS_BRANCH"="master" && make heroku
>>>>>>> 325e51aeb95a43c959df052ac5af38181f88a5a1

notifications:
  email: false
# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script
