language: python
python:
  - "3.8"
sudo: required
services:
  # -docker
env:
  global:
    - TRAVIS=true
#before_install:
install: true
# before_script:
script:
  - make dev_env
  - make test
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - source/*
  skip_cleanup: true
  on:
    tags: true

# after_failure:
# after_success:
  # - sh .travis/deploy_dockerhub.sh
  # - test "$TRAVIS_BRANCH"="master" && sh .travis_deploy_heroku.sh

# [OPTIONAL] before_deploy
# [OPTIONAL] deploy
# [OPTIONAL] after_deploy
# after_script
