version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend/Dockerfile
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/nginx.template:/etc/nginx/conf.d/default.conf
    image: hypertars/greloupis-frontend:latest

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    image: hypertars/greloupis-backend:latest