version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - ACCESS_KEY_ID1=${ACCESS_KEY_ID1}
        - SECRET_KEY1=${SECRET_KEY1}
        - ACCESS_KEY_ID2=${ACCESS_KEY_ID2}
        - SECRET_KEY2=${SECRET_KEY2}
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/configs/nginx.template:/etc/nginx/conf.d/default.conf.template
      - ./frontend/configs/nginx.conf:/etc/nginx/nginx/conf
    environment:
      - PORT=3000
    image: hypertars/greloupis-frontend:latest

  backend:
    restart: always
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PORT=5000
      - PROFILE="prod"
      - AWS_AUTH_KEY=${AWS_AUTH_KEY}
      - AWS_CLOUD_FRONT=${AWS_CLOUD_FRONT}
      - AWS_THUMBNAIL_FOLDER=${AWS_THUMBNAIL_FOLDER}
      - MONGO_DEV=${MONGO_DEV}
      - MONGO_TEST=${MONGO_TEST}
      - MONGO_PROD=${MONGO_PROD}
    image: hypertars/greloupis-backend:latest