version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(module)s - %(filename)s - %(funcName)s - %(lineno)d - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  debug_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/debug.log
    maxBytes: 10485760
    backupCount: 50
    encoding: utf8
  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/info.log
    maxBytes: 10485760
    backupCount: 50
    encoding: utf8
  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 50
    encoding: utf8
loggers:
  debug_logger:
    level: DEBUG
    handlers: [ console, debug_handler ]
    propagate: no
  info_logger:
    level: INFO
    handlers: [ console, info_handler ]
    propagate: no
  error_logger:
    level: ERROR
    handlers: [ console, error_handler ]
    propagate: no
root:
  level: DEBUG
  handlers: [ console, debug_handler, info_handler, error_handler ]