name: CI/CD

on:
  push:
  # pull_request:
  workflow_dispatch:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  DOCKER_USER: "hypertars"
  DOCKER_EMAIL: "hypertars@gmail.com"
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  BACKEND_BUILD: "greloupis-backend"
  FRONTEND_BUILD: "greloupis-frontend"
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_FRONTEND: "greloupis-frontend"
  HEROKU_APP_BACKEND: "greloupis-backend"
  HEROKU_EMAIL: "hypertars@gmail.com"

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: technote-space/auto-cancel-redundant-workflow@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python Version
      run: |
        python3 -V
        pip3 -V
    - name: Install Dependencies
      run: make dev_env
    - name: Run Tests
      run: make tests
    - name: Test Report
      run: |
        make report
        make coverage
  dockerize:
    name: Dockerize
    runs-on: ubuntu-18.04
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Push To Dockerhub
        run: make docker_push
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: [dockerize]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Deploy Frontend
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: $HEROKU_EMAIL
          api_key: $HEROKU_API_KEY
          app_name: $HEROKU_APP_FRONTEND
          dockerfile_path: frontend
      - name: Deploy Backend
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: $HEROKU_EMAIL
          api_key: $HEROKU_API_KEY
          app_name: $HEROKU_APP_BACKEND
          dockerfile_path: backend