name: Deploy

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy Frontend to Heroku
      - uses: actions/checkout@master
      - uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: "hypertars@gmail.com"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "greloupis-frontend"
          dockerfile_path: "frontend"
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy Backend to Heroku
      - uses: actions/checkout@master
      - uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          email: "hypertars@gmail.com"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "greloupis-backend"
          dockerfile_path: "backend"