name: Dockerize

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_USER: "hypertars"
  DOCKER_EMAIL: "hypertars@gmail.com"
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  BACKEND_BUILD: "greloupis-backend"
  FRONTEND_BUILD: "greloupis-frontend"

jobs:
  dockerize:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push To Dockerhub
        run: make docker_push